### ISSUE TITLE
Planet without user names

### ISSUE THREAD

**Issue by AndrewHain** [zerebubuth/planet-dump-ng#34]
As part of [GDPR compliance](https://wiki.openstreetmap.org/wiki/GDPR/Planet.osm_Migration) it is desirable to be able to produce planets with user names omitted.

**Comment by joto** [comment]
That is easily done with the `--clean` option in `osmium cat`. No need to change planet-dump-ng.

**Comment by zerebubuth** [comment]
I agree with @joto. Since `osmium` supports this directly, I don't think this feature needs to be in `planet-dump-ng`. At worst, adding an extra step will add a few minutes to planet generation, which is already a days-long process. (Also, I personally don't believe that removing this data is necessary, [but that's a different discussion](https://github.com/zerebubuth/openstreetmap-cgimap/issues/144#issuecomment-388939635)).
